Marian : my first script
nbiro/ausy_academy_2022 pull request #11
Opened 2022-09-28 22:00 UTC by mitumarian02

2022-09-30 10:07 UTC, nbiro requested changes

2022-09-30 10:07 UTC, nbiro commented on Marian/Task1_Scripting/Task1.sh
> +repoPath="/home/projectx/Desktop/gitBasics/ausy_academy_2022"
indentation

2022-09-30 10:07 UTC, nbiro commented on Marian/Task1_Scripting/Task1.sh
> +repoPath="/home/projectx/Desktop/gitBasics/ausy_academy_2022"
this code is the same for both implementation, please move duplicated code either to a separate function or just outside of a function

2022-10-02 19:31 UTC, mitumarian02 reviewed
Renamed the last commit and couldn't push without a pull that merged branches (i dont know)

2022-10-03 06:09 UTC, nbiro commented
> Renamed the last commit and couldn't push without a pull that merged branches (i dont know)

if you rename a commit, you need to use push -f or push --force-with-lease (google the difference pls)

2022-10-03 06:10 UTC, nbiro approved these changes

2022-10-03 06:10 UTC, merged